import os
from dotenv import load_dotenv
import logging

load_dotenv("./agentic_rag/config/envs/app_settings.env")
logging.info("Loaded crawford app_settings.env")

WORKER_AND_BATCH_SIZE = int(os.getenv("WORKER_AND_BATCH_SIZE"))
INPUT_DIR = os.getenv("INPUT_DIR")
APP_NAME = os.getenv("APP_NAME")
STATUS_PROCESSED = os.getenv("STATUS_PROCESSED")
STATUS_FAILED = os.getenv("STATUS_FAILED")
STATUS_IN_PROGRESS = os.getenv("STATUS_IN_PROGRESS")
MONGO_INFO_LOG_COLLECTION = os.getenv("MONGO_INFO_LOG_COLLECTION")
MONGO_ERROR_LOG_COLLECTION = os.getenv("MONGO_ERROR_LOG_COLLECTION")
MONGO_DOCUMENT_COLLECTION = os.getenv("MONGO_DOCUMENT_COLLECTION")
MONGO_MERGED_COLLECTION = os.getenv("MONGO_MERGED_COLLECTION")
MONGO_CLIENT_COLLECTION = os.getenv("MONGO_CLIENT_COLLECTION")
MONGO_CONFIGURATION_COLLECTION = os.getenv("MONGO_CONFIGURATION_COLLECTION")
MONGO_AGENTIC_RAG_COLLECTION = os.getenv("MONGO_AGENTIC_RAG_COLLECTION")
ENV_NAMES =  os.getenv("ENV_NAMES").split(",")

ENV_NAME = os.environ.get("ENVIRONMENT").lower()
WEBSITE_PORT = int(os.environ.get("WEBSITES_PORT"))
MONGO_CONNECTION_STRING = os.environ.get("MONGO_CONNECTION_STRING")
INSTRUMENTATION_KEY = os.environ.get("INSTRUMENTATION_KEY")
AZURE_OPENAI_SERVICE = os.environ.get("AZURE_OPENAI_SERVICE")
MONGO_DB = os.environ.get("MONGO_DB")
BLOB_ACCOUNT_NAME = os.environ.get("BLOB_ACCOUNT_NAME")
AZURE_OPENAI_CHATGPT_DEPLOYMENT = os.environ.get("AZURE_OPENAI_CHATGPT_DEPLOYMENT")
ADOBE_CLIENT_ID = os.environ.get("ADOBE_CLIENT_ID")
ADOBE_CLIENT_SECRET = os.environ.get("ADOBE_CLIENT_SECRET")
ACCOUNT_URL = 'https://' + BLOB_ACCOUNT_NAME + '.blob.core.windows.net'
